// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"StoryGoAPI/ent/migrate"

	"StoryGoAPI/ent/guestuser"
	"StoryGoAPI/ent/story"
	"StoryGoAPI/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// GuestUser is the client for interacting with the GuestUser builders.
	GuestUser *GuestUserClient
	// Story is the client for interacting with the Story builders.
	Story *StoryClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.GuestUser = NewGuestUserClient(c.config)
	c.Story = NewStoryClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		GuestUser: NewGuestUserClient(cfg),
		Story:     NewStoryClient(cfg),
		User:      NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		GuestUser: NewGuestUserClient(cfg),
		Story:     NewStoryClient(cfg),
		User:      NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		GuestUser.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.GuestUser.Use(hooks...)
	c.Story.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.GuestUser.Intercept(interceptors...)
	c.Story.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *GuestUserMutation:
		return c.GuestUser.mutate(ctx, m)
	case *StoryMutation:
		return c.Story.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// GuestUserClient is a client for the GuestUser schema.
type GuestUserClient struct {
	config
}

// NewGuestUserClient returns a client for the GuestUser from the given config.
func NewGuestUserClient(c config) *GuestUserClient {
	return &GuestUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `guestuser.Hooks(f(g(h())))`.
func (c *GuestUserClient) Use(hooks ...Hook) {
	c.hooks.GuestUser = append(c.hooks.GuestUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `guestuser.Intercept(f(g(h())))`.
func (c *GuestUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.GuestUser = append(c.inters.GuestUser, interceptors...)
}

// Create returns a builder for creating a GuestUser entity.
func (c *GuestUserClient) Create() *GuestUserCreate {
	mutation := newGuestUserMutation(c.config, OpCreate)
	return &GuestUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GuestUser entities.
func (c *GuestUserClient) CreateBulk(builders ...*GuestUserCreate) *GuestUserCreateBulk {
	return &GuestUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GuestUser.
func (c *GuestUserClient) Update() *GuestUserUpdate {
	mutation := newGuestUserMutation(c.config, OpUpdate)
	return &GuestUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GuestUserClient) UpdateOne(gu *GuestUser) *GuestUserUpdateOne {
	mutation := newGuestUserMutation(c.config, OpUpdateOne, withGuestUser(gu))
	return &GuestUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GuestUserClient) UpdateOneID(id int) *GuestUserUpdateOne {
	mutation := newGuestUserMutation(c.config, OpUpdateOne, withGuestUserID(id))
	return &GuestUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GuestUser.
func (c *GuestUserClient) Delete() *GuestUserDelete {
	mutation := newGuestUserMutation(c.config, OpDelete)
	return &GuestUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GuestUserClient) DeleteOne(gu *GuestUser) *GuestUserDeleteOne {
	return c.DeleteOneID(gu.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GuestUserClient) DeleteOneID(id int) *GuestUserDeleteOne {
	builder := c.Delete().Where(guestuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GuestUserDeleteOne{builder}
}

// Query returns a query builder for GuestUser.
func (c *GuestUserClient) Query() *GuestUserQuery {
	return &GuestUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGuestUser},
		inters: c.Interceptors(),
	}
}

// Get returns a GuestUser entity by its id.
func (c *GuestUserClient) Get(ctx context.Context, id int) (*GuestUser, error) {
	return c.Query().Where(guestuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GuestUserClient) GetX(ctx context.Context, id int) *GuestUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFollowed queries the followed edge of a GuestUser.
func (c *GuestUserClient) QueryFollowed(gu *GuestUser) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := gu.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(guestuser.Table, guestuser.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, guestuser.FollowedTable, guestuser.FollowedPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(gu.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GuestUserClient) Hooks() []Hook {
	return c.hooks.GuestUser
}

// Interceptors returns the client interceptors.
func (c *GuestUserClient) Interceptors() []Interceptor {
	return c.inters.GuestUser
}

func (c *GuestUserClient) mutate(ctx context.Context, m *GuestUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GuestUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GuestUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GuestUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GuestUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GuestUser mutation op: %q", m.Op())
	}
}

// StoryClient is a client for the Story schema.
type StoryClient struct {
	config
}

// NewStoryClient returns a client for the Story from the given config.
func NewStoryClient(c config) *StoryClient {
	return &StoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `story.Hooks(f(g(h())))`.
func (c *StoryClient) Use(hooks ...Hook) {
	c.hooks.Story = append(c.hooks.Story, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `story.Intercept(f(g(h())))`.
func (c *StoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Story = append(c.inters.Story, interceptors...)
}

// Create returns a builder for creating a Story entity.
func (c *StoryClient) Create() *StoryCreate {
	mutation := newStoryMutation(c.config, OpCreate)
	return &StoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Story entities.
func (c *StoryClient) CreateBulk(builders ...*StoryCreate) *StoryCreateBulk {
	return &StoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Story.
func (c *StoryClient) Update() *StoryUpdate {
	mutation := newStoryMutation(c.config, OpUpdate)
	return &StoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StoryClient) UpdateOne(s *Story) *StoryUpdateOne {
	mutation := newStoryMutation(c.config, OpUpdateOne, withStory(s))
	return &StoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StoryClient) UpdateOneID(id int) *StoryUpdateOne {
	mutation := newStoryMutation(c.config, OpUpdateOne, withStoryID(id))
	return &StoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Story.
func (c *StoryClient) Delete() *StoryDelete {
	mutation := newStoryMutation(c.config, OpDelete)
	return &StoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StoryClient) DeleteOne(s *Story) *StoryDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StoryClient) DeleteOneID(id int) *StoryDeleteOne {
	builder := c.Delete().Where(story.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StoryDeleteOne{builder}
}

// Query returns a query builder for Story.
func (c *StoryClient) Query() *StoryQuery {
	return &StoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStory},
		inters: c.Interceptors(),
	}
}

// Get returns a Story entity by its id.
func (c *StoryClient) Get(ctx context.Context, id int) (*Story, error) {
	return c.Query().Where(story.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StoryClient) GetX(ctx context.Context, id int) *Story {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPostedby queries the postedby edge of a Story.
func (c *StoryClient) QueryPostedby(s *Story) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(story.Table, story.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, story.PostedbyTable, story.PostedbyColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StoryClient) Hooks() []Hook {
	return c.hooks.Story
}

// Interceptors returns the client interceptors.
func (c *StoryClient) Interceptors() []Interceptor {
	return c.inters.Story
}

func (c *StoryClient) mutate(ctx context.Context, m *StoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Story mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPosted queries the posted edge of a User.
func (c *UserClient) QueryPosted(u *User) *StoryQuery {
	query := (&StoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(story.Table, story.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.PostedTable, user.PostedColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFollowedBy queries the followedBy edge of a User.
func (c *UserClient) QueryFollowedBy(u *User) *GuestUserQuery {
	query := (&GuestUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(guestuser.Table, guestuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.FollowedByTable, user.FollowedByPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		GuestUser, Story, User []ent.Hook
	}
	inters struct {
		GuestUser, Story, User []ent.Interceptor
	}
)
