// Code generated by ent, DO NOT EDIT.

package ent

import (
	"StoryGoAPI/ent/guestuser"
	"StoryGoAPI/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuestUserDelete is the builder for deleting a GuestUser entity.
type GuestUserDelete struct {
	config
	hooks    []Hook
	mutation *GuestUserMutation
}

// Where appends a list predicates to the GuestUserDelete builder.
func (gud *GuestUserDelete) Where(ps ...predicate.GuestUser) *GuestUserDelete {
	gud.mutation.Where(ps...)
	return gud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gud *GuestUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gud.sqlExec, gud.mutation, gud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gud *GuestUserDelete) ExecX(ctx context.Context) int {
	n, err := gud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gud *GuestUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(guestuser.Table, sqlgraph.NewFieldSpec(guestuser.FieldID, field.TypeInt))
	if ps := gud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gud.mutation.done = true
	return affected, err
}

// GuestUserDeleteOne is the builder for deleting a single GuestUser entity.
type GuestUserDeleteOne struct {
	gud *GuestUserDelete
}

// Where appends a list predicates to the GuestUserDelete builder.
func (gudo *GuestUserDeleteOne) Where(ps ...predicate.GuestUser) *GuestUserDeleteOne {
	gudo.gud.mutation.Where(ps...)
	return gudo
}

// Exec executes the deletion query.
func (gudo *GuestUserDeleteOne) Exec(ctx context.Context) error {
	n, err := gudo.gud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{guestuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gudo *GuestUserDeleteOne) ExecX(ctx context.Context) {
	if err := gudo.Exec(ctx); err != nil {
		panic(err)
	}
}
