// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GuestUser is the predicate function for guestuser builders.
type GuestUser func(*sql.Selector)

// Story is the predicate function for story builders.
type Story func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
